name: "Pre-commit autoupdate"

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: write

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
        with:
          ref: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.11

      - name: Install pre-commit
        run: pip install pre-commit

      - uses: leafo/gh-actions-lua@v10
      - uses: leafo/gh-actions-luarocks@v4

      - name: Run autoupdate
        run: pre-commit autoupdate

      - name: Run pre-commit
        run: pre-commit run --all-files

      - uses: peter-evans/create-pull-request@v6.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore-update-pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "Update pre-commit hooks"
          body: |
            # Update pre-commit hooks

            - Update pre-commit hooks to the latest version.
          delete-branch: true
          labels: |
            dependencies
            python
